# Generated by Django 2.2.6 on 2020-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cert_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cert_name',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
