# Generated by Django 2.2.6 on 2020-05-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20200529_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_loc',
            new_name='job_location',
        ),
    ]
