# Generated by Django 2.2.6 on 2020-05-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20200529_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='user',
        ),
    ]
